name: Block Non-Admin Pushes to Main

on:
  push:
    branches: [ main ]

jobs:
  check-permissions:
    runs-on: ubuntu-latest
    steps:
      - name: Check if pusher is admin
        id: check_admin
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              // Get the pusher's permission level
              const { data: permission } = await github.rest.repos.getCollaboratorPermissionLevel({
                owner: context.repo.owner,
                repo: context.repo.repo,
                username: context.actor
              });
              
              if (permission.permission !== 'admin') {
                core.setFailed("❌ Only repository admins can push directly to main. Please create a pull request.");
              }
            } catch (error) {
              core.setFailed("Error checking permissions: " + error.message);
            }