name: Block Direct Pushes to Main

on:
  push:
    branches: [ main ]

jobs:
  block:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct push
        run: |
          echo "❌ Direct pushes to 'main' are not allowed!"
          echo "Please create a Pull Request instead."
          exit 1
